-- ==============================================================================
-- NOVA MVC-4.0 Supabase 資料庫初始化腳本
-- 請將此腳本複製並貼上至 Supabase 的 SQL Editor 中執行
-- ==============================================================================

-- 1. 開啟向量擴充功能
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. 建立【教材緩存表】(llm_generation_cache)
CREATE TABLE IF NOT EXISTS llm_generation_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL,
    news_context TEXT,
    teacher_card_content TEXT,
    examiner_quiz_content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    update_count INTEGER DEFAULT 0,
    word_embedding vector(384),
    context_embedding vector(384),
    example_embedding vector(384),
    raw_example_en TEXT,
    raw_quiz_en TEXT
);

-- 3. 建立【SRS 進度追蹤表】(user_srs_progress)
CREATE TABLE IF NOT EXISTS user_srs_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE REFERENCES llm_generation_cache(word) ON DELETE CASCADE,
    easiness_factor DOUBLE PRECISION DEFAULT 2.5,
    interval INTEGER DEFAULT 0,
    next_review_date TIMESTAMPTZ DEFAULT NOW(), 
    last_reviewed_at TIMESTAMPTZ,
    repetition_count INTEGER DEFAULT 0
);

-- 4. 建立效能索引 (HNSW 向量搜尋與日期排序)
CREATE INDEX IF NOT EXISTS word_embedding_idx ON llm_generation_cache USING hnsw (word_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS context_embedding_idx ON llm_generation_cache USING hnsw (context_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS example_embedding_idx ON llm_generation_cache USING hnsw (example_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS user_srs_review_date_idx ON user_srs_progress (next_review_date);

-- ==============================================================================
-- 5. 建立 RAG 向量搜尋函數 (RPC)
-- ==============================================================================

-- (A) 單字大腦搜尋
CREATE OR REPLACE FUNCTION match_words (
  query_embedding vector(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (word text, similarity float)
LANGUAGE sql STABLE
AS $$
  SELECT word, 1 - (word_embedding <=> query_embedding) AS similarity
  FROM llm_generation_cache
  WHERE 1 - (word_embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
$$;

-- (B) 生活情境大腦搜尋
CREATE OR REPLACE FUNCTION match_examples (
  query_embedding vector(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (word text, similarity float)
LANGUAGE sql STABLE
AS $$
  SELECT word, 1 - (example_embedding <=> query_embedding) AS similarity
  FROM llm_generation_cache
  WHERE 1 - (example_embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
$$;

-- (C) 新聞時事大腦搜尋
CREATE OR REPLACE FUNCTION match_contexts (
  query_embedding vector(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (word text, similarity float)
LANGUAGE sql STABLE
AS $$
  SELECT word, 1 - (context_embedding <=> query_embedding) AS similarity
  FROM llm_generation_cache
  WHERE 1 - (context_embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
$$;

-- ==============================================================================
-- 腳本結束
-- ==============================================================================